import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/Navbar";

 
const pretandard = localFont({
  src: '../../../public/Pretendard-Regular.woff2',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="smooth-scrolling">
      <body
        className={`${pretandard.className} antialiased`}
      >
        <Navbar/>
        <div>{children}</div>
      </body>
    </html>
  );
}
