import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretandard = localFont({
  src: "../../public/Pretendard-Regular.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="smooth-scrolling">
      <body className={`${pretandard.className} antialiased`}>{children}</body>
    </html>
  );
}
